### ISSUE TITLE
Arbeidsforhold UUID validering

### ISSUE THREAD

**Issue by junnae** [navikt/folketrygdloven-beregningsgrunnlag-regelmodell#10]
Hei
Før så var arbeidsforhold ID bare en vilkårlig String.. Nå valideres det at den må være UUID. Er det noe grunn til det? En ting er at testene våre brekker i beregningsmodulen, men vi har funksjonalitet som er avhengig av å kunne sette den verdien til en vilkårlig string - Vi har trikset det til for å løse noe funksjonalitet som vi ikke fikk løst i reglene

**Comment by junnae** [comment]
Reglene har vi alltid hatt som en dependency, selv om pakken var bygd fra FPSAK

**Comment by junnae** [comment]
Men koden rundt, map til og fra regel har vi selv, rundt

**Comment by junnae** [comment]
Vi har bare ikke oppdatert reglene siden UUID ble påkrevd

**Comment by espenjv** [comment]
@junnae Om du veit kva som skal gjerast her kan du gjerne lage ein pull request sjølv, og setje nokon av oss på review :)

**Comment by junnae** [comment]
Jeg tror det bare er 1-2 linjer med kode ja .. Jeg skal se om jeg får laget en PR selv

**Comment by mrsladek** [comment]
Virker at den brukes kun i test klasser derfor er den ok til å bli fjernet da Arbeidsforhold forventer en String.

**Comment by mrsladek** [comment]
PR merged
