### ISSUE TITLE
about delen i repot

### ISSUE THREAD

**Issue by MikAoJk** [navikt/folketrygdloven-beregningsgrunnlag-regelmodell#292]
Hei!
Eg ble litt forvirret over beskrivelsen av repoet.
Da det står "Lov om folketrygd kapittel 8", eg trodde det var sykepenger eller?

Er dette repoet ment får denne delen av loven?
https://lovdata.no/dokument/NL/lov/1997-02-28-19/KAPITTEL_9#KAPITTEL_9

**Comment by espenjv** [comment]
Repoet dekker beregningsregler for kapittel 8, 9 og 14 i folketrygdloven. Det brukes også av sykepenger (sjå repoet https://github.com/navikt/spberegning). Kapittel 9 og kapittel 14 viser til kapittel 8 for beregningsregler.
